### ISSUE TITLE
[Education Backend] - Clean up views.py code

### ISSUE THREAD

**Issue by Enether** [two-man-army/deadline#26]
Apply fetch_models decorator where applicable and finish TODOs there

**Comment by Enether** [comment]
@nemalp can you take a look at the code here 
https://github.com/two-man-army/deadline/blob/feature/education-platform/deadline_/education/views.py

I'm contemplating if its worth it to split the views in a more organized way, i.e course_views, lesson_views, hw_task_views
The file is getting big (500 lines) and while admittedly it does look scarier on github, it's still maintainable in an IDE, although I don't know at which point it's worth to re-structure the organization of the view functions.

Another question is how would we re-structure it, maybe a views folder with course_views.py and etc in it?

Main questions:
At what point is it worth it to re-structure (750 lines, 1000, now)?
Do you agree in structuring them like views/course_views.py and etc

**Comment by Enether** [comment]
Seemingly done, waiting on answer from @nemalp

**Comment by nemalp** [comment]
@Enether 

> At what point is it worth it to re-structure (750 lines, 1000, now)?
IMO now. Moving the views in separate files will improve code management and readability

> Do you agree in structuring them like views/course_views.py and etc
This seems to be the best option. Something like:
![views](https://user-images.githubusercontent.com/8751970/28492543-633dbbe2-6f0e-11e7-8ddd-633fc199ae5d.png)

**Comment by Enether** [comment]
Exactly, done
44eaf6d8f582101807e24cbd2f577b463cb90b44
