### ISSUE TITLE
New endpoint for retrieving all subcategories with their respective information.

### ISSUE THREAD

**Issue by nemalp** [two-man-army/deadline#39]
We need an API for retrieving the subcat information in order to display it on the subcategories page.

Imagine you are on Algorithms. We should be able to retrieve all subcategories and each one should come with the following:

1. Current badge i.e. Novice, Expert etc.

2. Experience required to upgrade the badge. Ex. from Novice to Expert (say 400exp to Expert).

3. Completed challenges. For instance 8/10, 10/10 etc.

4. The data from point 3 in percentage (%)

![image](https://user-images.githubusercontent.com/8751970/29206358-4d6dbf02-7e8a-11e7-9fad-7604ba621c2e.png)

**Comment by Enether** [comment]
You've got it, but I'm going to implement so you have to do some calculation on the front-end

Here is a SubCategory sample
```
{'name': Recursion
                         'proficiency': {'name': Master,
                                         'user_score': 500},
                         'next_proficiency': {'name': Legend,
                                              'needed_percentage': 100},
                         'max_score': 1000, 'challenge_count':100, 'solved_challenges_count': 51}
```
For the 85% Completed, you can simply take what percentage `solved_challenges_count` is out of `challenge_count`
`max_score` is the maximum score you can attain for that SubCategory. 

To calculate how much XP is needed to the next proficiency, do this:
Given the current user's score (proficiency.user_score) and the max_score, you can calculate how much percentage he has completed (SCORE WISE), simply get what percentage `user_score` is of `max_score`.

To calculate how much XP is needed to the next, you know the user has completed say 85% from the above calculation, you simply take the leftover percentage - (`needed_percentage` - 85%) and take that percentage from the `max_score`

**Comment by Enether** [comment]
1c0ad2b
Close this issue if you agree, @nemalp
