### ISSUE TITLE
Fetching subcategories should be done by category name instead of id.

### ISSUE THREAD

**Issue by nemalp** [two-man-army/deadline#42]
We need to change the current implementation for fetching subcategories. This is required in order to bypass local storage. 

Current endpoint: **/challenges/categories/{category_id}/subcategories**.

Required endpoint: **/challenges/categories/{category_name}/subcategories**

The response should contain the name of the main category as well.

**Comment by Enether** [comment]
Done, seemingly. The endpoint is extended and allows for both ID and name querying 
I don't get why you'd nee the name of the main category when you query with it?

**Comment by nemalp** [comment]
You are right. I don't need it.
