### ISSUE TITLE
Add a DB table for completed challenges

### ISSUE THREAD

**Issue by Enether** [two-man-army/deadline#46]
The idea is: once a user completes a challenge, save that to a table, that would look something like this:
[ user_id | challenge_id ]
An additional idea could be to attach the challenge score there.

We need this table, because:
1. Faster query times (Just one query and you know if the user has solved the challenge.) as you now have to query Submissions for a submission from the user which has as much score as the challenge's.
2. For an easy way to showcase how many challenges the user has solved from a given difficulty, as shown in the bottom left here - https://trello-attachments.s3.amazonaws.com/5989b492c63790ac931c4d04/598cba44c0182204eb1baea4/17b5b2102a8d0690882932319e5abcf2/Dashboard.jpg

**Comment by arushi011** [comment]
-------------QUERY TO CREATE TABLE-----------------------
CREATE TABLE tblUserChallengeStatus (
user_id VARCHAR(50) ,
challenge_id VARCHAR(50)
)

-----------------QUERY TO CREATE STORED PROCEDURE TO INSERT/UPDATE TABLE---------------------
CREATE PROCEDURE uspSaveChallengeStatus
@user_id VARCHAR(50) = ''
@challenge_id VARCHAR(50)=''
AS
BEGIN
IF EXISTS (select * from tblUserChallengeStatus where user_id = @user_id )
UPDATE tblUserChallengeStatus SET challenge_id  = @challenge_id WHERE user_id = @user_id
ELSE
insert into tblUserChallengeStatus (user_id,challenge_id ) values (@user_id,@challenge_id)
END

**Comment by sanchit97** [comment]
Isn't this supposed to be a PR? Or do you want copy pasting here itself?(Why?)

**Comment by Enether** [comment]
@arushi011 Sorry, but that's not helpful. I need the models in the code itself, the migrations ran and the connections (e.g complete challenge -> create record, unit tests) done

**Comment by saratlingamarla** [comment]
@Enether So a class in accounts/models.py for this? and method to support updating score and completion status, right?

**Comment by Enether** [comment]
@saratlingamarla as well as tests to see that when a user completes a challenge it creates the DB record. You can create a first draft and I'll guide you on what you might have missed. Please take some time to look around the code and maybe the unit tests, as they best describe the project

**Comment by saratlingamarla** [comment]
thanks @Enether, I'll start working on this.

**Comment by saratlingamarla** [comment]
@Enether, when I run python manage.py migrate, I get this:
def fetch_subcategory_proficiency(self, subcategory_id) -> 'UserSubcategoryProficiency':
                                                            ^
SyntaxError: invalid syntax

Also, my IDE shows multiple errors in all models.py, is this a Django version issue, any idea?

**Comment by Enether** [comment]
What Python version are you running?!

**Comment by Enether** [comment]
We use **Python 3.6**. I just updated `README.md` to specify this.

**Comment by saratlingamarla** [comment]
oh boy,sorry did not see that

**Comment by saratlingamarla** [comment]
then maybe also update the README saying pip3 install -r requirements.txt instead of pip
